#!/usr/bin/env python3
"""The mechanical half of the brief self-check, as a command that fails.

    python3 brief-lint.py <brief>.html        exit 1 on any defect
    python3 brief-lint.py --self-check        known-answer cases, no network

Every check here corresponds to a rule already written in SKILL.md or one of the
reference files. They are restated as code for one reason, measured 2026-09-07: a
brief shipped missing the answers block, the definitions markup, three of four part
ledes and every contents note, and the author had read the prose rule for two of
those and applied it wrongly. A rule nothing refuses on is not a rule.

Scoped to what markup can prove. Whether the standfirst is paid off, whether the
summary reads cold, and whether a term earns its place in defs-out are judgement
and stay with the author.

ponytail: regex over the rendered HTML, no parser. The page is generated by one
renderer we control, so its shape is known. If a hand-authored brief ever fails
here for shape rather than substance, that is when this grows an HTML parser.
"""
import re
import sys
import pathlib

RUNTIME = re.compile(r"<style\b.*?</style>|<script\b.*?</script>", re.S | re.I)


def body(html):
    """The authored page with the inlined runtime removed.

    Every count here is wrong without it: brief.css alone carries dozens of em
    dashes and the string `summary-page`, and it is inlined into every brief.
    """
    return RUNTIME.sub("", html)


def check(html):
    b = body(html)
    out = []

    def bad(msg):
        out.append(msg)

    if len(re.findall(r"<h1\b", b)) != 1:
        bad(f"{len(re.findall(r'<h1', b))} <h1> elements, expected exactly 1")

    parts = len(re.findall(r'<h2 class="part"', b))
    ledes = len(re.findall(r'class="partlede"', b))
    if parts and ledes != parts:
        bad(f"{parts} part(s) but {ledes} part lede(s) — every part opens with one")

    toc = re.findall(r'<nav class="toc">(.*?)</nav>', b, re.S)
    if toc:
        entries = toc[0].count("<li")
        notes = toc[0].count("tnote")
        if notes < entries:
            bad(f"{entries} contents entries but {notes} tnote(s) — "
                f"a bare list tells the reader nothing they cannot get by scrolling")
        ids = set(re.findall(r'id="([^"]+)"', b))
        dead = [h for h in re.findall(r'href="#([^"]+)"', toc[0]) if h not in ids]
        if dead:
            bad(f"dead contents anchor(s): {', '.join(dead[:5])}")
    elif len(re.findall(r'class="brief-section"', b)) > 4:
        bad("more than four sections and no contents list")

    # The answers block. A brief with no answers declares that by saying so in the
    # source; silence is the failure this catches, because the commonest miss is a
    # findings report assuming the exception covers it.
    if 'class="answers"' not in b and "data-brief-no-answers" not in html:
        bad("no answers block — the questions are the ones the brief ANSWERS, never "
            "the ones it asks. Set data-brief-no-answers on <body> if it truly has none")

    # Definitions, if the brief has the section at all, uses the block markup.
    if re.search(r'data-sec="definitions"', b) and "defs-in" not in b:
        bad("a Definitions section with no defs-in/defs-out markup — "
            "see reference/definitions-block.md")

    # Footnote markers and references travel together, both ways.
    fns = set(re.findall(r'<sup class="fn"><a href="#([^"]+)"', b))
    if fns and 'data-sec="references"' not in b:
        bad(f"{len(fns)} footnote marker(s) and no References section")
    ids = set(re.findall(r'id="([^"]+)"', b))
    dangling = sorted(f for f in fns if f not in ids)
    if dangling:
        bad(f"footnote marker(s) pointing at nothing: {', '.join(dangling[:5])}")

    if "—" in b:
        n = b.count("—")
        where = re.search(r".{40}—.{40}", b)
        bad(f"{n} em dash(es) in the page: ...{where.group(0).strip()}..."
            if where else f"{n} em dash(es) in the page")

    return out


def main(argv):
    if not argv or argv[0] == "--self-check":
        return self_check()
    path = pathlib.Path(argv[0])
    found = check(path.read_text(encoding="utf-8", errors="replace"))
    if not found:
        print(f"brief-lint: {path.name} clean")
        return 0
    print(f"brief-lint: {len(found)} defect(s) in {path.name}")
    for f in found:
        print(f"  - {f}")
    return 1


GOOD = """<html><style>body{}/* — */</style><body>
<main><h1>T</h1><p class="sub">s</p>
<dl class="answers"><dt>Q</dt><dd>A</dd></dl>
<nav class="toc"><ol><li><a href="#s-a">A</a> <span class="tnote">what</span></li></ol></nav>
<h2 class="part">One</h2><p class="partlede">lede</p>
<section class="brief-section" id="s-a" data-sec="a"><p>x<sup class="fn"><a href="#r1">1</a></sup></p></section>
<section class="brief-section" data-sec="references"><li id="r1">apa</li></section>
</main></body></html>"""


def self_check():
    fails = []
    if check(GOOD):
        fails.append(f"the good page should be clean: {check(GOOD)}")
    cases = [
        ("no answers block", GOOD.replace('<dl class="answers"><dt>Q</dt><dd>A</dd></dl>', ""), "answers block"),
        ("missing part lede", GOOD.replace('<p class="partlede">lede</p>', ""), "part lede"),
        ("no tnote", GOOD.replace('<span class="tnote">what</span>', ""), "tnote"),
        ("dead anchor", GOOD.replace('href="#s-a"', 'href="#s-gone"'), "dead contents anchor"),
        ("em dash in body", GOOD.replace("<p>x<sup", "<p>a — b<sup"), "em dash"),
        ("dangling footnote", GOOD.replace('<li id="r1">apa</li>', "apa"), "pointing at nothing"),
        ("prose definitions", GOOD.replace('data-sec="a"', 'data-sec="definitions"'), "defs-in"),
    ]
    for name, page, want in cases:
        got = " ".join(check(page))
        if want not in got:
            fails.append(f"{name}: expected {want!r}, got {got!r}")
    # The runtime must not be scanned: an em dash in inlined CSS is not the author's.
    if check(GOOD.replace("/* — */", "/* — — — */")):
        fails.append("em dashes inside <style> were counted; the runtime must be stripped")
    if fails:
        for f in fails:
            print("FAIL ", f)
        print(f"\nFAILED  {len(fails)} failure(s)")
        return 1
    print(f"PASS  {len(cases) + 2} cases, 0 failures")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
