#!/usr/bin/env python3
"""The mechanical half of the brief self-check, as a command that fails.

    python3 brief-lint.py <brief>.html        exit 1 on any defect
    python3 brief-lint.py --self-check        known-answer cases, no network

Every check here corresponds to a rule already written in SKILL.md or one of the
reference files. They are restated as code for one reason, measured 2026-09-07: a
brief shipped missing the answers block, the definitions markup, three of four part
ledes and every contents note, and the author had read the prose rule for two of
those and applied it wrongly. A rule nothing refuses on is not a rule.

Scoped to what markup can prove. Whether the standfirst is paid off, whether the
summary reads cold, and whether a term earns its place in defs-out are judgement
and stay with the author.

ponytail: regex over the rendered HTML, no parser. The page is generated by one
renderer we control, so its shape is known. If a hand-authored brief ever fails
here for shape rather than substance, that is when this grows an HTML parser.
"""
import re
import sys
import pathlib

RUNTIME = re.compile(r"<style\b.*?</style>|<script\b.*?</script>", re.S | re.I)
TAGS = re.compile(r"<[^>]+>")
TOC = re.compile(r'<nav class="toc">.*?</nav>', re.S)
QSEC = re.compile(r'<section class="q"[^>]*>.*?</section>', re.S)
SECTION = re.compile(r"<section\b[^>]*>.*?</section>", re.S)
# The verdict is two sentences, the call and its price. 400 characters is the
# ceiling this file enforces, because sentence splitting breaks on "e.g." and on
# a decimal, and a character count cannot be argued with.
VERDICT_MAX = 400
# Disclosures a "Recommended" tag has to be read against. The linter cannot judge
# whether the tag survives the disclosure, so it asks for a human look.
DISCLOSURES = ("tie", "proxy", "back-cast", "approximated")


def text(fragment):
    """Visible text of an HTML fragment, whitespace collapsed."""
    return re.sub(r"\s+", " ", TAGS.sub(" ", fragment)).strip()


def verdict(b):
    """The first paragraph after the answers block, or None.

    The contents list is dropped first: it renders between the answers block and
    the summary page and it opens each part with a <p> of its own.
    """
    m = re.search(r'class="answers"', b)
    if not m:
        return None
    p = re.search(r"<p\b[^>]*>(.*?)</p>", TOC.sub(" ", b[m.end():]), re.S)
    return text(p.group(1)) if p else None


def body(html):
    """The authored page with the inlined runtime removed.

    Every count here is wrong without it: brief.css alone carries dozens of em
    dashes and the string `summary-page`, and it is inlined into every brief.
    """
    return RUNTIME.sub("", html)


def check(html):
    b = body(html)
    out = []

    def bad(msg):
        out.append(msg)

    if len(re.findall(r"<h1\b", b)) != 1:
        bad(f"{len(re.findall(r'<h1', b))} <h1> elements, expected exactly 1")

    parts = len(re.findall(r'<h2 class="part"', b))
    ledes = len(re.findall(r'class="partlede"', b))
    if parts and ledes != parts:
        bad(f"{parts} part(s) but {ledes} part lede(s) — every part opens with one")

    toc = re.findall(r'<nav class="toc">(.*?)</nav>', b, re.S)
    if toc:
        entries = toc[0].count("<li")
        notes = toc[0].count("tnote")
        if notes < entries:
            bad(f"{entries} contents entries but {notes} tnote(s) — "
                f"a bare list tells the reader nothing they cannot get by scrolling")
        ids = set(re.findall(r'id="([^"]+)"', b))
        dead = [h for h in re.findall(r'href="#([^"]+)"', toc[0]) if h not in ids]
        if dead:
            bad(f"dead contents anchor(s): {', '.join(dead[:5])}")
    elif len(re.findall(r'class="brief-section"', b)) > 4:
        bad("more than four sections and no contents list")

    # The answers block. A brief with no answers declares that by saying so in the
    # source; silence is the failure this catches, because the commonest miss is a
    # findings report assuming the exception covers it.
    if 'class="answers"' not in b and "data-brief-no-answers" not in html:
        bad("no answers block — the questions are the ones the brief ANSWERS, never "
            "the ones it asks. Set data-brief-no-answers on <body> if it truly has none")

    # Definitions, if the brief has the section at all, uses the block markup.
    if re.search(r'data-sec="definitions"', b) and "defs-in" not in b:
        bad("a Definitions section with no defs-in/defs-out markup — "
            "see reference/definitions-block.md")

    # Footnote markers and references travel together, both ways.
    fns = set(re.findall(r'<sup class="fn"><a href="#([^"]+)"', b))
    if fns and 'data-sec="references"' not in b:
        bad(f"{len(fns)} footnote marker(s) and no References section")
    ids = set(re.findall(r'id="([^"]+)"', b))
    dangling = sorted(f for f in fns if f not in ids)
    if dangling:
        bad(f"footnote marker(s) pointing at nothing: {', '.join(dangling[:5])}")

    # The verdict, directly under the answers block: the call, then its price.
    if 'class="answers"' in b:
        v = verdict(b)
        if v is None:
            bad("verdict rule: no paragraph after the answers block. The first paragraph "
                "there is the verdict, stating the call and then its price")
        elif len(v) > VERDICT_MAX:
            bad(f"verdict rule: the verdict paragraph is {len(v)} characters, over the "
                f"{VERDICT_MAX} character ceiling for two sentences, the call and its price")

    # A decision question states the crux in plain words, which means a number.
    for sec in QSEC.findall(b):
        if "DECIDE" not in text(sec) and "data-decision" not in sec.split(">", 1)[0]:
            continue
        if not re.search(r"\d", text(re.sub(r'<span class="qid">[^<]*</span>', " ", sec))):
            qid = re.search(r'data-q="([^"]+)"', sec)
            bad(f"decision-crux rule: {qid.group(1) if qid else 'a DECIDE question'} carries no "
                f"number. Restate the crux in plain words: the cost, the benefit, the likelihood")

    if "—" in b:
        n = b.count("—")
        where = re.search(r".{40}—.{40}", b)
        bad(f"{n} em dash(es) in the page: ...{where.group(0).strip()}..."
            if where else f"{n} em dash(es) in the page")

    return out


def warnings(html):
    """Things a human has to judge, so they never change the exit code.

    A "Recommended" tag has to hold against every disclosure in the same brief.
    Whether a tie, a proxy, a back-cast or an approximation undercuts the tag is a
    reading of the evidence, which regex cannot do, so this asks rather than fails.
    """
    out = []
    for sec in SECTION.findall(body(html)):
        if 'class="rec"' not in sec and "is-rec" not in sec:
            continue
        t = text(sec).lower()
        hit = [d for d in DISCLOSURES if d in t]
        if hit:
            name = re.search(r'(?:data-q|data-sec)="([^"]+)"', sec)
            out.append(f"Recommended-consistency rule: {name.group(1) if name else 'a section'} "
                       f"tags an option Recommended and discloses a {hit[0]}. Read the tag against "
                       f"that disclosure by hand")
    return out


def main(argv):
    if not argv or argv[0] in ("--self-check", "--selftest"):
        return self_check()
    path = pathlib.Path(argv[0])
    html = path.read_text(encoding="utf-8", errors="replace")
    found = check(html)
    warned = warnings(html)
    if found:
        print(f"brief-lint: {len(found)} defect(s) in {path.name}")
        for f in found:
            print(f"  - {f}")
    else:
        print(f"brief-lint: {path.name} clean")
    for w in warned:
        print(f"  ? {w}")
    return 1 if found else 0


GOOD = """<html><style>body{}/* — */</style><body>
<main><h1>T</h1><p class="sub">s</p>
<dl class="answers"><dt>Q</dt><dd>A</dd></dl>
<nav class="toc"><ol><li><a href="#s-a">A</a> <span class="tnote">what</span></li></ol></nav>
<h2 class="part">One</h2><p class="partlede">lede</p>
<section class="brief-section" id="s-a" data-sec="a"><p>x<sup class="fn"><a href="#r1">1</a></sup></p></section>
<section class="brief-section" data-sec="references"><li id="r1">apa</li></section>
</main></body></html>"""


Q = ('<section class="q" id="s-q1" data-q="Q1"><h3><span class="qid">Q1</span> '
     'DECIDE: which road</h3><p>{}</p></section>')
Q_BAD = GOOD.replace("</main>", Q.format("The mechanism, and nothing it costs.") + "</main>")
Q_OK = GOOD.replace("</main>", Q.format(
    "Road A costs $4k and buys cover on the 30% case.") + "</main>")
REC = GOOD.replace("</main>", '<section class="q" data-q="Q2"><ul class="options">'
                   '<li class="is-rec">a) ship it <span class="rec">Recommended</span></li></ul>'
                   "<p>The gate used a proxy for the real measure.</p></section></main>")


def self_check():
    fails = []
    if check(Q_OK):
        fails.append(f"a DECIDE question carrying numbers should be clean: {check(Q_OK)}")
    if warnings(GOOD):
        fails.append(f"no Recommended tag, so no warning: {warnings(GOOD)}")
    if "Recommended-consistency rule: Q2" not in " ".join(warnings(REC)):
        fails.append(f"Recommended beside a proxy should warn: {warnings(REC)}")
    if check(REC):
        fails.append(f"the Recommended check warns, it never fails: {check(REC)}")
    if check(GOOD):
        fails.append(f"the good page should be clean: {check(GOOD)}")
    cases = [
        ("no answers block", GOOD.replace('<dl class="answers"><dt>Q</dt><dd>A</dd></dl>', ""), "answers block"),
        ("missing part lede", GOOD.replace('<p class="partlede">lede</p>', ""), "part lede"),
        ("no tnote", GOOD.replace('<span class="tnote">what</span>', ""), "tnote"),
        ("dead anchor", GOOD.replace('href="#s-a"', 'href="#s-gone"'), "dead contents anchor"),
        ("em dash in body", GOOD.replace("<p>x<sup", "<p>a — b<sup"), "em dash"),
        ("dangling footnote", GOOD.replace('<li id="r1">apa</li>', "apa"), "pointing at nothing"),
        ("prose definitions", GOOD.replace('data-sec="a"', 'data-sec="definitions"'), "defs-in"),
        ("no verdict after the answers block",
         GOOD.replace('<p class="partlede">lede</p>', "")
             .replace("<p>x<sup", "<div>x<sup").replace('</a></sup></p>', "</a></sup></div>"),
         "no paragraph after the answers block"),
        ("verdict over the ceiling",
         GOOD.replace(">lede<", ">" + "word " * 120 + "<"),
         "over the 400 character ceiling"),
        ("DECIDE question with no number", Q_BAD, "decision-crux rule: Q1"),
    ]
    for name, page, want in cases:
        got = " ".join(check(page))
        if want not in got:
            fails.append(f"{name}: expected {want!r}, got {got!r}")
    # The runtime must not be scanned: an em dash in inlined CSS is not the author's.
    if check(GOOD.replace("/* — */", "/* — — — */")):
        fails.append("em dashes inside <style> were counted; the runtime must be stripped")
    if fails:
        for f in fails:
            print("FAIL ", f)
        print(f"\nFAILED  {len(fails)} failure(s)")
        return 1
    print(f"PASS  {len(cases) + 6} cases, 0 failures")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
